#! /bin/bash

LIB="-D_MPI -D_CUDA -D_SCALAPACK -D_SLEPC -D_PAR_IO -D_HDF5_IO -D_HDF5_LIB"
COMP=" -D_FORTRAN_US -D_DRIVER_TEST -D_C_US"
CWD=`pwd`
BIN="-D_example_driver";
case "$1"
in
clean) BIN="CLEAN";;
esac
#
if [ $BIN = "CLEAN" ]
then
 file_list=`find . -type f | grep -E '\.o|\.x|\.mod|\.f90|\.a' |grep -v '\.object' | grep -v .swp` 
 for file in $file_list; do
  echo $file
  rm -f $file
 done
 exit
fi

DIRS='src/interface src/main src/options example/options'

INCS="-I$CWD/example/include/"
LIBa="$CWD/lib/libdriver.a"

for dir in $DIRS; do
 cd $dir
 file_list=`find . -maxdepth 1 -type f | grep -E '\.c' |grep -v .swp`
 for file in $file_list; do
  echo $dir/$file
  mpicc $COMP $LIB $BIN -c $file -I$CWD/src/headers $INCS
 done
 if [ $dir = "src/interface" ]
 then
  file_list='mod_C_driver.F C_driver_transfer.F'
  for file in $file_list; do
   F_file=`echo $file | sed 's/.F/.f90/g'`
   cp $file $F_file
   echo $dir/$file
   mpif90 $COMP $LIB $OPT $BIN -c $F_file -I$CWD/src/headers  
  done
 fi
 find . -type f | grep -E '\.o|\.mod' | xargs ar -r $LIBa
 cd $CWD/
done

cd src/driver
mpicc $COMP $LIB $OPT $BIN -c driver.c -I $CWD/src/headers $INCS
cd $CWD

cp src/interface/c_driver.mod include
cp example/main.F main.f90
mpif90  -c main.f90 -I./include
rm -f driver.x
mpif90 -o driver.x src/driver/driver.o main.o $LIBa -I./include $INCS

#./driver.x -h
#./driver.x -x -J jobA1,jobBBB2 -O ODIRONE -I TESTONE -C COMUNICONE -F input_file -nompi -noopenmp -setup -opt chi -Q
#./driver.x -x -optics c -y d -J jobA1,jobBBB2 -O ODIRONE -I TESTONE -C COMUNICONE -F input_file -t

